#!/bin/bash

if [[ -z "$1" ]]; then
    echo "Usage: $0 module [module...]"
    exit 1
fi

mydir=$(dirname $0)

PROMPT="${PROMPT:-Enter Machine Owner Key (MOK) passphrase: }"
KERNELVER=${KERNELVER:-$(uname -r)}

do_sign() {
    /lib/modules/$KERNELVER/build/scripts/sign-file sha256 $mydir/MOK.priv $mydir/MOK.der "$1"
}

for module in $@; do
    echo "Signing module: $module"
    # For XZ/GZ/ZST:
    module_basename="$(echo "$module" | sed -e 's/\.xz$//' -e 's/\.gz$//' -e 's/\.zst//')"
    module_suffix="$(echo "$module" | sed -e 's/.*\.//g')"
    if [[ "$module_suffix" == "xz" ]]; then
        unxz $module
        do_sign $module_basename
        xz -f $module_basename
    elif [[ "$module_suffix" == "gz" ]]; then
        gunzip $module
        do_sign $module_basename
        gzip -9f $module_basename
    elif [[ "$module_suffix" == "zst" ]]; then
        unzstd --rm -f $module
        do_sign $module_basename
        zstd --rm -f $module_basename
    else
        do_sign $module
    fi    
done
