#!/bin/bash

PACKAGE_NAME="tuxedo-drivers"
PACKAGE_VERSION="$(rpm -q ${PACKAGE_NAME} --qf '%{VERSION}\n')"
KERNEL_VERSION="$(uname -r)"
ARCH="$(uname -m)"

echo "Building DKMS modules"
dkms build "${PACKAGE_NAME}/${PACKAGE_VERSION}" || exit 1
echo "Signing modules"
"$(dirname "$0")/manual-sign" $(find "/var/lib/dkms/${PACKAGE_NAME}/${PACKAGE_VERSION}/${KERNEL_VERSION}/${ARCH}/module/" -name '*.ko' -o -name '*.ko.xz' -o -name '*.ko.gz' -o -name '*.ko.zst') || exit 1
echo "Installing modules"
dkms install "${PACKAGE_NAME}/${PACKAGE_VERSION}" || exit 1
echo "Loading modules"
for file in $(find "/var/lib/dkms/${PACKAGE_NAME}/${PACKAGE_VERSION}/${KERNEL_VERSION}/${ARCH}/module/" -name '*.ko' -o -name '*.ko.xz' -o -name '*.ko.gz' -o -name '*.ko.zst')
do :
    MODULENAME="$(basename "$file")"
    MODULENAME="$(basename -s .xz "$MODULENAME")"
    MODULENAME="$(basename -s .gz "$MODULENAME")"
    MODULENAME="$(basename -s .zst "$MODULENAME")"
    MODULENAME="$(basename -s .ko "$MODULENAME")"
    modprobe "$MODULENAME"
done
